### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by danifromecuador** [bohaz/recipe_app#11]
## In this project we are 2 people, @bohaz  and @danifromecuador 

This is the [link](https://github.com/users/bohaz/projects/1) to the project's kanban board

**Comment by Munsa1** [comment]
Hi @danifromecuador @bohaz , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Created Cards :heavy_check_mark: 
Used An Issues Link For Submission :heavy_check_mark: 
Work Distributed In A Fair Way ✔️ 


## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly ensure that all your cards have a description as per the requirement
![image](https://github.com/bohaz/recipe_app/assets/81932478/c279a163-d29e-4a54-bb1a-78721acc67b5)
The following cards have no description:
- Food list card
- Recipes list card
- Public Recipe List card
- Recipe Details card
- General Shopping List View card
- N+1 Queries card
- Create A Navigation Menu Card
- Write Unit And Integration Tests card

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by OyePriscilla** [comment]
Hi @danifromecuador and @bohaz 👏 👏 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
All the cards have description ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
